# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/132AfHDj6P0R9l11A7rpVVwBnk4ZALCOG

# write a program which accpet princple ,rate and time form user and print the simple interest .the formula to calculate simple interest is:simple interest = principle X rate X time /100 solutioin
"""

principle = float(input("enter the principle amount"))
rate = float(input("enter the rate of interest "))
time = float(input("enter the time"))
simple = principle*rate*time/100
print(simple)